### GOOD GET request to retrieve all users
GET http://localhost:3000/users
Content-Type: application/json

> {%
    client.test("Get all users successfully", function () {
        // Controleer of de status 200 is
        client.assert(response.status === 200, "Response status is not 200");

    });
%}
