### GET request to example server
GET http://localhost:3000/won-auctions
Authorization: Bearer {{jwt_token}}
Accept: application/json

> {%
    client.test("Valid request returns 200 OK", function () {
        client.assert(response.status === 200, "Expected status 200, but got " + response.status);
        client.assert(response.body.wonAuctions.length > 0, "Expected some won auctions to be returned.");
    });
    client.test("Response contains totalPayment", function () {
        client.assert(response.body.totalPayment !== undefined, "Expected totalPayment field in response.");
    });
%}

### BAD GET request with invalid token

GET http://localhost:3000/won-auctions
Authorization: Bearer hahahmal234324234
Accept: application/json

> {%
    client.test("No won auctions returns 401 Not Found", function () {
        client.assert(response.status === 401, "Expected status 401, but got " + response.status);
    });
%}
